[package]
name = "soulbound-meta"
version = "0.0.0"
authors = [ "",]
edition = "2018"
publish = false

[dependencies.soulbound]
path = ".."

[dependencies.elrond-wasm]
version = "0.34.0"

[dependencies.elrond-wasm-debug]
version = "0.34.0"
